import {
  AirVent, Award, Baby, BadgeCheck, Bath, Bed, Bike, Blocks, Book, Briefcase,
  Brush, Bug, Building2, Bus, Cake, Calculator, Calendar, Camera, Car, Cat,
  ChartBar, ChefHat, Clipboard, Clock, Code, Coffee, CircleDollarSign, Dog,
  Drill, Droplet, Dumbbell, Fan, Film, FileText, Flower2, Gavel, Globe,
  GraduationCap, Guitar, Hammer, Handshake, Heart, Hotel, House, Languages,
  Laptop, LayoutGrid, Leaf, Lightbulb, MapPin, Megaphone, Mic, Monitor, Music,
  Package, Paintbrush, Palette, PartyPopper, PawPrint, PenTool, Phone, Pizza,
  Plane, Plug, Printer, Recycle, Refrigerator, Router, Ruler, Scale, School,
  Scissors, Settings, Shirt, ShieldCheck, ShoppingCart, Smartphone, Sofa,
  Sparkles, Sprout, SprayCan, Star, Stethoscope, Store, Sun, Tags, Trash2,
  Trees, TrendingUp, Truck, Tv, Users, Utensils, Video, Wallet, Warehouse,
  WashingMachine, Wifi, Wrench, Zap,
} from 'lucide-react';

const ICON_MAP = {

  spray: SprayCan,
  droplet: Droplet,
  bolt: Zap,
  'air-conditioning': AirVent,
  sparkles: Sparkles,
  camera: Camera,
  palette: Palette,
  code: Code,
  book: Book,
  barbell: Dumbbell,
  confetti: PartyPopper,
  truck: Truck,
  home: House,
  briefcase: Briefcase,
  hammer: Hammer,
  calculator: Calculator,
  language: Languages,
  scissors: Scissors,
  flower: Flower2,

  category: LayoutGrid,
  tool: Wrench,
  tools: Wrench,
  wrench: Wrench,
  brush: Brush,
  paint: Paintbrush,
  wash: WashingMachine,
  'wash-machine': WashingMachine,
  plug: Plug,
  bulb: Lightbulb,
  car: Car,
  bike: Bike,
  bus: Bus,
  plane: Plane,
  paw: PawPrint,
  dog: Dog,
  cat: Cat,
  heart: Heart,
  stethoscope: Stethoscope,
  'first-aid-kit': Stethoscope,
  school: School,
  'graduation-cap': GraduationCap,
  music: Music,
  guitar: Guitar,
  microphone: Mic,
  video: Video,
  movie: Film,
  'shopping-cart': ShoppingCart,
  'building-store': Store,
  package: Package,
  'shield-check': ShieldCheck,
  star: Star,
  users: Users,
  'users-group': Users,
  handshake: Handshake,
  message: Megaphone,
  phone: Phone,
  'map-pin': MapPin,
  calendar: Calendar,
  clock: Clock,
  settings: Settings,
  wifi: Wifi,
  router: Router,
  'device-laptop': Laptop,
  'device-desktop': Monitor,
  'device-mobile': Smartphone,
  'device-tv': Tv,
  printer: Printer,
  leaf: Leaf,
  plant: Sprout,
  seeding: Sprout,
  tree: Trees,
  sun: Sun,
  bed: Bed,
  sofa: Sofa,
  bath: Bath,
  building: Building2,
  'building-warehouse': Warehouse,
  hotel: Hotel,
  'chef-hat': ChefHat,
  'tools-kitchen': Utensils,
  cake: Cake,
  coffee: Coffee,
  pizza: Pizza,
  fridge: Refrigerator,
  'air-balloon': Fan,
  fan: Fan,
  ruler: Ruler,
  pencil: PenTool,
  'file-text': FileText,
  clipboard: Clipboard,
  gavel: Gavel,
  scale: Scale,
  wallet: Wallet,
  'currency-rupee': CircleDollarSign,
  'chart-bar': ChartBar,
  'trending-up': TrendingUp,
  bug: Bug,
  recycle: Recycle,
  trash: Trash2,
  shirt: Shirt,
  baby: Baby,
  blocks: Blocks,
  drill: Drill,
  world: Globe,
  certificate: Award,
  'rosette-discount-check': BadgeCheck,
  tag: Tags,
  tags: Tags,
};

export const DEFAULT_CATEGORY_ICON = LayoutGrid;

export function getCategoryIcon(name) {
  if (!name || typeof name !== 'string') return DEFAULT_CATEGORY_ICON;

  const slug = name.trim().toLowerCase().replace(/^ti[-\s]/, '');
  if (ICON_MAP[slug]) return ICON_MAP[slug];

  const base = slug.replace(/-(filled|off|outline)$/, '');
  if (ICON_MAP[base]) return ICON_MAP[base];

  return DEFAULT_CATEGORY_ICON;
}

export const CATEGORY_ICON_SUGGESTIONS = [
  'droplet', 'bolt', 'hammer', 'spray', 'air-conditioning', 'sparkles',
  'camera', 'palette', 'code', 'book', 'barbell', 'confetti', 'truck',
  'home', 'briefcase', 'calculator', 'language', 'scissors', 'flower',
];
